spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  type-aliases-package: com.transwrap.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  config: classpath:log4j2.xml